export const countConstants = {
	COUNT_UPDATE_REQUEST: 'COUNT_CHANGE_REQUEST',
	COUNT_UPDATE_SUCCESS: 'COUNT_CHANGE_SUCCESS',
	COUNT_UPDATE_FAILURE: 'COUNT_CHANGE_FAILURE',

	COUNT_REQUEST_REQUEST: 'COUNT_REQUEST_REQUEST',
	COUNT_REQUEST_SUCCESS: 'COUNT_REQUEST_SUCCESS',
	COUNT_REQUEST_FAILURE: 'COUNT_REQUEST_FAILURE'
};
